### ISSUE TITLE
asm.js

### ISSUE THREAD

**Issue by refset** [tromp/cuckoo#14]
Have you already thought about whether it could be compiled to run in a browser? Would a hand-optimised js implementation be a terrible idea?

This is very interesting, thanks for sharing it!

**Comment by tromp** [comment]
dear Jeremy,

> Have you already thought about whether it could be compiled to run in a browser? Would a hand-optimised js implementation be a terrible idea?
>
> This is very interesting, thanks for sharing it!

Of course I'm very keen on getting it to run in browsers,
and I've looked hard at javascript and other languages compilable
to javascript.
But the big stumbling block is lack of support for 64 bit ints.
Cuckoo Cycle is very big on 64-bit ints, and expressing those as
pairs of 32-bit ints is not only extremely painful in source code, but
also a recipe for dismal performance.
I've not been able to find a language with 64-bit ints that compiles to js,
and would at least avoid the source code pain.

So I'm waiting for webasm to mature, since it looks like it will have
full 64-bit support...

regards,
-John

**Comment by refset** [comment]
Thank you for the prompt and detailed reply. I hope we get there soon :)

**Comment by halo** [comment]
> I hope we get there soon :)

Looks like it's coming to Chrome https://github.com/tc39/proposal-bigint/issues/53#issuecomment-451677909
